monolog:
    channels: ['security', 'user']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: info
            channels: ["security"]
        user:
            type: stream
            path: "%kernel.logs_dir%/user.log"
            level: info
            channels: ["user"]
