services:
  db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - auth-network

  app:
    build: .
    container_name: symfony-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - auth-network
    tty: true

volumes:
  db-data:

networks:
  auth-network:
